version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: resume_db
      MYSQL_USER: resume_user
      MYSQL_PASSWORD: resume_password
    ports:
      - '3306:3306'
